# -*- coding: utf-8 -*-
# Tool configuration for the Ansible Runner Kit.

[tool.black]
line-length = 79

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 79
select = ["E", "F", "I"]

[tool.mypy]
strict = true
pretty = true
verbosity = 0
disallow_incomplete_defs = true
disallow_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
ignore_missing_imports = true

[tool.pylint.messages_control]
ignored-modules = ["pydantic"]

[tool.pylint.format]
max-line-length = 79

[tool.pylint.'reports=no']
output-format = "text"
