---

- name: Check connectivity and DNS resolution for all hosts
  hosts: all
  gather_facts: false
  vars:
    connectivity_timeout: 5

  tasks:
    - name: Check connectivity
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: "{{ connectivity_timeout }}"
        state: started
      ignore_errors: true

