---
sshd_settings:
  - name: PubkeyAuthentication
    value: "yes"
  # - name: PermitRootLogin
  #  value: "yes"
  # - name: PasswordAuthentication
  #  value: "yes"
  # - name: ChallengeResponseAuthentication
  #  value: "no"
  # - name: UsePAM
  #   value: "yes"
  # - name: UseDNS
  #   value: "no"
