---
- name: Check SSHD Configurations
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check if sshd_config exists
      ansible.builtin.stat:
        path: /etc/ssh/sshd_config
      register: sshd_config_stat

    - name: Report missing sshd_config
      ansible.builtin.debug:
        msg: "Host: {{ inventory_hostname }} | sshd_config is missing"
      when: not sshd_config_stat.stat.exists

    - name: Check SSHD Configurations
      ansible.builtin.command:
        cmd: "sshd -T -f /etc/ssh/sshd_config"
      register: sshd_config_check
      ignore_errors: true
      changed_when: false
      when: sshd_config_stat.stat.exists

    - name: Display bad or misconfigured SSHD Configurations
      ansible.builtin.debug:
        msg: "Host: {{ inventory_hostname }} | Error: {{ sshd_config_check.stderr }}"
      when: sshd_config_check.rc != 0
